export const enum Keys {
  COMMENTS_KEY = "COMMENTS_STORAGE",
  STORAGE_KEY = "POSTS_STATE",
  POSTS_KEY = "POSTS_STORAGE",
  SAVED_POSTS_KEY = "SAVED_POSTS_STORAGE",
  POST_ACTIONS_KEY = "POST_ACTIONS_STORAGE",
}
